version: "3"

services:
  server:
    build:
      context: ../server
      dockerfile: .docker/Dockerfile.test
    env_file:
      - ../.docker/.env
    environment:
      - MONGO_URI=mongodb://${MONGO_INITDB_ROOT_USERNAME}:${MONGO_INITDB_ROOT_PASSWORD}@${MONGO_URI}
      - PORT=${PORT}
      - NODE_ENV=${NODE_ENV}
    ports:
      - ${PORT}:${PORT}
    command: node src/index.js
    links:
      - db
    restart: always

  client:
    build:
      context: ../client
      dockerfile: .docker/Dockerfile.test
    env_file:
      - ../.docker/.env
    ports:
      - 80:80
    links:
      - server
    restart: always

  db:
    image: mongo
    env_file:
      - ../.docker/.env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      # Map physical volume to virtual for data persistence
      # On server could be /data/db
      # For this case we will create a Docker volume and use it instead
      # You need to run docker volume create yourproject-dbdata
      - board-dbdata:/data/db
# Add this to include data volume for mongo
# Confirm this is working later
volumes:
  board-dbdata:
